const logger = require('../utils/logger');

const generateChatReport = async (userId, messages) => {
    try {
        // Simple Markdown report generator
        let report = `# AgriAssist Chat Report\n\n`;
        report += `**User ID:** ${userId}\n`;
        report += `**Date:** ${new Date().toLocaleDateString()}\n\n`;
        report += `---\n\n`;

        messages.forEach((msg, index) => {
            const role = msg.role === 'user' ? 'User' : 'AgriAssist';
            report += `### ${role} (${new Date(msg.timestamp).toLocaleTimeString()})\n`;
            report += `${msg.content}\n\n`;
        });

        report += `---\n\n*This report was generated by AgriAssist AI.*`;

        return {
            title: `Report_${new Date().getTime()}`,
            content: report,
            format: 'markdown'
        };
    } catch (error) {
        logger.error('Report Generation Error:', error);
        throw error;
    }
};

module.exports = {
    generateChatReport
};
